package com.example.demo.controller.empleado;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.demo.dao.EmpleadoRepository;
import com.example.demo.model.Beneficiario;
import com.example.demo.model.Empleado;

@Controller // This means that this class is a Controller
@RequestMapping("/empleadoRespaldo") // This means URL's start with /empleado (after Application path)
public class EmpleadoControllerRespaldo {
  @Autowired // This means to get the bean called EmpleadoRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private EmpleadoRepository empleadoRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewEmpleado (@RequestParam String fullname
      , @RequestParam String apPaterno, 
      @RequestParam String apMaterno, 
      @RequestParam String rfc, 
      @RequestParam String edoCivil,@RequestParam String sexo) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Empleado n = new Empleado();
    n.setNombre(fullname);
    n.setApPaterno(apPaterno);
    n.setApMaterno(apMaterno);
    n.setEstadoCivil(edoCivil);
    n.setSexo(sexo);    
    n.setRFC(rfc);
    Beneficiario b=new Beneficiario("levi","juarez","hernandez","h",25,1);    
    n.addBeneficiario(b);    
    empleadoRepository.save(n);
    return "Saved"; 
  }


  @PostMapping(path="/addFrom") // Map ONLY POST Requests
  public String addNewEmpleado (@ModelAttribute("empleado")Empleado e) {    
    empleadoRepository.save(e);
    return "redirect:/empleado/index";
  }

  @GetMapping("/registrar") // Map ONLY POST Requests
  public String   agregar (Model model) {
    Empleado n = new Empleado();
    model.addAttribute("empleado", n);   
    return "registrarEmpleado"; 
  }

  @GetMapping("/modificar/{id}") 
  public String   modificar (@PathVariable int id,Model model) {
    model.addAttribute("empleado", empleadoRepository.findById(id).get());
    return "prueba/modificarEmpleado";  
    
  }

  @PostMapping("/actualizar/{id}") 
  public String   modificar (@PathVariable int id,@ModelAttribute("empleado")Empleado e,Model model) {
    empleadoRepository.save(e);
    return "redirect:/empleado/index";    
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Empleado> getAll() {
    // This returns a JSON or XML with the users
    return empleadoRepository.findAll();
  }


  @GetMapping("/index")
public String showUserList(Model model) {
    model.addAttribute("empleados", empleadoRepository.findAll());
    
    return "index";
}



  @GetMapping(path="/allhql")
  public @ResponseBody Iterable<Empleado> getAllBYHQL() {
    // This returns a JSON or XML with the users
    return empleadoRepository.findAllByHQL();
  }

  

  @GetMapping("/one/{id}")
  public @ResponseBody Optional<Empleado> getById(@PathVariable int id) {
    // This returns a JSON or XML with the users
    if(id<100)
        return empleadoRepository.findById(id);
    else
        throw new EmpleadoNotfoundException();
  }

  @GetMapping("/onehql/{id}")
  public @ResponseBody Optional<Empleado> getByIdHQL(@PathVariable int id) {
    // This returns a JSON or XML with the users
    return empleadoRepository.findByIdHQL(id);
  }

  @PutMapping(path = "/update/{id}")
  public @ResponseBody String updateEmpleado( @PathVariable int id,
  @RequestParam String fullname
  , @RequestParam String apPaterno, 
  @RequestParam String apMaterno, 
  @RequestParam String rfc, 
  @RequestParam String edoCivil,
  @RequestParam String sexo){    

    Empleado n = empleadoRepository.findById(id).get();    
    if(n==null){
      throw new EmpleadoNotfoundException();      
    }else{
      n.setNombre(fullname);
      n.setApPaterno(apPaterno);
      n.setApMaterno(apMaterno);
      n.setEstadoCivil(edoCivil);
      n.setSexo(sexo);    
      n.setRFC(rfc);
      empleadoRepository.save(n);
          return "Actualizado";
    }
  }



  @GetMapping(path= "/eliminar/{id}")
  public String eliminarEmpleado(@PathVariable int id){
    Empleado e=empleadoRepository.findById(id).get();    
    if(e==null){
      return "redirect:empleado/index";
    }else{
          empleadoRepository.delete(e);
          return "redirect:/empleado/index";
    }
  }


  @DeleteMapping(path= "/delete/{id}")
  public @ResponseBody String deleteEmpleado(@PathVariable int id){
    Empleado e=empleadoRepository.findById(id).get();    
    if(e==null){
      return "error";
    }else{
          empleadoRepository.delete(e);
          return "eliminado";
    }
  }

}